# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Ing_electronica_unal/7_semestre/digital_electronics_2/project_4/project_4.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_auto_pc_5/zynq7000_preset_auto_pc_5.xci
# IP: The module: 'zynq7000_preset_auto_pc_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Ing_electronica_unal/7_semestre/digital_electronics_2/project_4/project_4.gen/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_auto_pc_5/zynq7000_preset_auto_pc_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq7000_preset_auto_pc_5'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Ing_electronica_unal/7_semestre/digital_electronics_2/project_4/project_4.srcs/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_auto_pc_5/zynq7000_preset_auto_pc_5.xci
# IP: The module: 'zynq7000_preset_auto_pc_5' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Ing_electronica_unal/7_semestre/digital_electronics_2/project_4/project_4.gen/sources_1/bd/zynq7000_preset/ip/zynq7000_preset_auto_pc_5/zynq7000_preset_auto_pc_5_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq7000_preset_auto_pc_5'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
