# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pines.xdc

# Block Designs: bd/zynq7000_preset/zynq7000_preset.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset || ORIG_REF_NAME==zynq7000_preset} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_processing_system7_0_0/zynq7000_preset_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_processing_system7_0_0 || ORIG_REF_NAME==zynq7000_preset_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_rst_ps7_0_50M_0/zynq7000_preset_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_rst_ps7_0_50M_0 || ORIG_REF_NAME==zynq7000_preset_rst_ps7_0_50M_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_dlmb_v10_0/zynq7000_preset_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_dlmb_v10_0 || ORIG_REF_NAME==zynq7000_preset_dlmb_v10_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_ilmb_v10_0/zynq7000_preset_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_ilmb_v10_0 || ORIG_REF_NAME==zynq7000_preset_ilmb_v10_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_dlmb_bram_if_cntlr_0/zynq7000_preset_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==zynq7000_preset_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_ilmb_bram_if_cntlr_0/zynq7000_preset_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==zynq7000_preset_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_lmb_bram_0/zynq7000_preset_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_lmb_bram_0 || ORIG_REF_NAME==zynq7000_preset_lmb_bram_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_microblaze_0_axi_intc_0/zynq7000_preset_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_microblaze_0_axi_intc_0 || ORIG_REF_NAME==zynq7000_preset_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_microblaze_0_xlconcat_0/zynq7000_preset_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_microblaze_0_xlconcat_0 || ORIG_REF_NAME==zynq7000_preset_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_axi_intc_0_0/zynq7000_preset_axi_intc_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_axi_intc_0_0 || ORIG_REF_NAME==zynq7000_preset_axi_intc_0_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_axi_bram_ctrl_0_0/zynq7000_preset_axi_bram_ctrl_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_axi_bram_ctrl_0_0 || ORIG_REF_NAME==zynq7000_preset_axi_bram_ctrl_0_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_axi_bram_ctrl_0_bram_0/zynq7000_preset_axi_bram_ctrl_0_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_axi_bram_ctrl_0_bram_0 || ORIG_REF_NAME==zynq7000_preset_axi_bram_ctrl_0_bram_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_axi_gpio_0_0/zynq7000_preset_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_axi_gpio_0_0 || ORIG_REF_NAME==zynq7000_preset_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_axi_timer_0_0/zynq7000_preset_axi_timer_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_axi_timer_0_0 || ORIG_REF_NAME==zynq7000_preset_axi_timer_0_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_mdm_1_0/zynq7000_preset_mdm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_mdm_1_0 || ORIG_REF_NAME==zynq7000_preset_mdm_1_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_microblaze_0_0/zynq7000_preset_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_microblaze_0_0 || ORIG_REF_NAME==zynq7000_preset_microblaze_0_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_xbar_0/zynq7000_preset_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_xbar_0 || ORIG_REF_NAME==zynq7000_preset_xbar_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_auto_pc_5/zynq7000_preset_auto_pc_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_auto_pc_5 || ORIG_REF_NAME==zynq7000_preset_auto_pc_5} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_auto_pc_6/zynq7000_preset_auto_pc_6.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_auto_pc_6 || ORIG_REF_NAME==zynq7000_preset_auto_pc_6} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_auto_pc_0/zynq7000_preset_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_auto_pc_0 || ORIG_REF_NAME==zynq7000_preset_auto_pc_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_auto_pc_1/zynq7000_preset_auto_pc_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_auto_pc_1 || ORIG_REF_NAME==zynq7000_preset_auto_pc_1} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_auto_pc_2/zynq7000_preset_auto_pc_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_auto_pc_2 || ORIG_REF_NAME==zynq7000_preset_auto_pc_2} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_auto_pc_3/zynq7000_preset_auto_pc_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_auto_pc_3 || ORIG_REF_NAME==zynq7000_preset_auto_pc_3} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_auto_pc_4/zynq7000_preset_auto_pc_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_auto_pc_4 || ORIG_REF_NAME==zynq7000_preset_auto_pc_4} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_s00_mmu_0/zynq7000_preset_s00_mmu_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_s00_mmu_0 || ORIG_REF_NAME==zynq7000_preset_s00_mmu_0} -quiet] -quiet

# IP: bd/zynq7000_preset/ip/zynq7000_preset_ps7_0_axi_periph_0/zynq7000_preset_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zynq7000_preset_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynq7000_preset_ps7_0_axi_periph_0} -quiet] -quiet

# XDC: d:/Ing_electronica_unal/7_semestre/digital_electronics_2/project_4/project_4.gen/sources_1/bd/zynq7000_preset/zynq7000_preset_ooc.xdc
