# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Ing_electronica_unal/7_semestre/digital_electronics_2/digital-2-lab/project/processor_hw/processor_hw.srcs/sources_1/bd/zynq_ejemplo/ip/zynq_ejemplo_xbar_0/zynq_ejemplo_xbar_0.xci
# IP: The module: 'zynq_ejemplo_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Ing_electronica_unal/7_semestre/digital_electronics_2/digital-2-lab/project/processor_hw/processor_hw.gen/sources_1/bd/zynq_ejemplo/ip/zynq_ejemplo_xbar_0/zynq_ejemplo_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_ejemplo_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/Ing_electronica_unal/7_semestre/digital_electronics_2/digital-2-lab/project/processor_hw/processor_hw.srcs/sources_1/bd/zynq_ejemplo/ip/zynq_ejemplo_xbar_0/zynq_ejemplo_xbar_0.xci
# IP: The module: 'zynq_ejemplo_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Ing_electronica_unal/7_semestre/digital_electronics_2/digital-2-lab/project/processor_hw/processor_hw.gen/sources_1/bd/zynq_ejemplo/ip/zynq_ejemplo_xbar_0/zynq_ejemplo_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_ejemplo_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
