# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Usuario/Desktop/modificaciones/digital-2-lab/project/modificacion/modificacion.srcs/sources_1/bd/zynq_ejemplo/ip/zynq_ejemplo_auto_pc_0/zynq_ejemplo_auto_pc_0.xci
# IP: The module: 'zynq_ejemplo_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Usuario/Desktop/modificaciones/digital-2-lab/project/modificacion/modificacion.gen/sources_1/bd/zynq_ejemplo/ip/zynq_ejemplo_auto_pc_0/zynq_ejemplo_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_ejemplo_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Usuario/Desktop/modificaciones/digital-2-lab/project/modificacion/modificacion.srcs/sources_1/bd/zynq_ejemplo/ip/zynq_ejemplo_auto_pc_0/zynq_ejemplo_auto_pc_0.xci
# IP: The module: 'zynq_ejemplo_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Usuario/Desktop/modificaciones/digital-2-lab/project/modificacion/modificacion.gen/sources_1/bd/zynq_ejemplo/ip/zynq_ejemplo_auto_pc_0/zynq_ejemplo_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynq_ejemplo_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
